---
title: "ct_env_spills"
output: html_document
date: "2024-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(tidyverse)
library(janitor)
library(lubridate)
```

```{r}
#Loading CSV and standardizing column header names
spills <- read_csv("spills.csv") |>
  clean_names()
```
```{r}
#Taking out 2024 because not enough data has been recorded yet, and then grouping by year to calculate how many spills reported per year
spills_by_year <- spills |>
  filter (year != "2024") |>
  group_by(year) |>
  summarise (
    spill_number = n()
  )

spills_by_year
```
```{r}
#Exporting the new grouped table
spills_by_year |> write_csv("spills_by_year.csv")
```

```{r}
#Looking at 2001, because most spills happened then 
spills_2001 <- spills |>
  filter (year == "2001") |> 
  group_by (release_date_and_time) |>
  summarise(
    count = n()
  ) |>
  filter (count > 1) |>
  arrange(desc(count))

#Examining the dates with a lot of spills reported in 2001
spills_individual_2001 <- spills |>
  filter (year == "2001") 
```

